import:
  - gocodebox/lifterlms:.config/travis/main.yml
  # - gocodebox/lifterlms:.config/travis/e2e.yml

install:
  - ./vendor/bin/llms-tests plugin lifterlms

jobs:
  include:
  - name: "Test OpenAPI Spec"
    language: node_js
    node_js: lts/*
    before_install:
    install:
      - npm ci
    script:
      - npm run test
  - stage: deploy
    language: node_js
    node_js: lts/*
    if: branch = trunk AND env(GH_TOKEN) IS present
    before_install:
    install:
      - npm ci
    script: npm run build && npm run gh-pages
