openapi: 3.0.0
info:
  version: 1.0.0
  title: LifterLMS REST API
  description: >-
    # Introduction

    LifterLMS (LLMS) is fully integrated with the [WordPress REST API](https://developer.wordpress.org/rest-api/). This allows LifterLMS data to be created, read, updated, and deleted using requests in JSON format and using WordPress REST API Authentication methods and standard HTTP verbs which are understood by most HTTP clients.

    ## Requirements

    To use the latest version of the REST API you must be using the following:

      + LifterLMS [@version]+.
      + WordPress 5.2+.
      + Pretty permalinks in `Settings -> Permalinks` so that the custom endpoints are supported. **Default permalinks will not work.**
      + An SSL certificate.

    ## Errors

    asrtasrtarst

    ## Pagination

    asrtastarstarst

    # Authentication

    Lorem ipsum...

    <!-- ReDoc-Inject: <security-definitions> -->

  x-logo:
    altText: LifterLMS
    url: "https://gocodebox.github.io/lifterlms-brand/assets/img/png/logo/lifterlms-logo.png"
    href: "https://lifterlms.com/"
servers:
  - url: /wp-json/llms/v1
security:
  - BasicAuth: []
