openapi: 3.0.0
info:
  version: 1.0.0
  title: LifterLMS REST API
  description: >-
    # Introduction

    LifterLMS (LLMS) is fully integrated with the [WordPress REST API](https://developer.wordpress.org/rest-api/). This allows LifterLMS data to be created, read, updated, and deleted using requests in JSON format and using WordPress REST API Authentication methods and standard HTTP verbs which are understood by most HTTP clients.

    ## Requirements

    To use the latest version of the REST API you must be using the following:

      + LifterLMS [@version]+.
      + WordPress 5.2+.
      + Pretty permalinks in `Settings -> Permalinks` so that the custom endpoints are supported. **Default permalinks will not work.**
      + An SSL certificate.

    ## Errors

    asrtasrtarst

    # Authentication

    Lorem ipsum...

    <!-- ReDoc-Inject: <security-definitions> -->

  x-logo:
    altText: LifterLMS
    url: "https://gocodebox.github.io/lifterlms-brand/assets/img/png/logo/lifterlms-logo.png"
    href: "https://lifterlms.com/"

servers:
  - url: /wp-json/llms/v1

security:
  - BasicAuth: []

tags:

  - name: Courses
    description: |
      The courses API allows you to create, view, update, and delete courses.

  - name: Enrollments
    description: |
      Enrollments are used to track a student's access to content on your website.

      The enrollments API allows you to create, view, update, and delete student enrollments.

  - name: Instructors
    description: |
      Instructors are members of your site who have the ability to create and manage LMS content and students. Instructors may be Adminstators, LMS Managers, Instructors, and Instructors Assistants.

      The instructors API allows you to create, view, update, and delete student accounts.

  - name: Students
    description: |
      Students are members of your site who are (or were) enrolled in your courses and memberships. Students can be any WordPress user account on your site (not exclusively the "student" role).

      The students API allows you to create, view, update, and delete student accounts  as well as view information about the student's LMS content.


# x-tagGroups:
#   - name: Courses
#     tags:
#       - Courses

#   - name: Students
#     tags:
#       - Students
