openapi: 3.0.0
info:
  version: 1.0.0
  title: LifterLMS REST API
  description: >-
    # Introduction

    LifterLMS (LLMS) is fully integrated with the [WordPress REST API](https://developer.wordpress.org/rest-api/). This allows LifterLMS data to be created, read, updated, and deleted using requests in JSON format and using WordPress REST API Authentication methods and standard HTTP verbs which are understood by most HTTP clients.

    ## Requirements

    To use the latest version of the REST API you must be using the following:

      + LifterLMS [@version]+.
      + WordPress 5.2+.
      + Pretty permalinks in `Settings -> Permalinks` so that the custom endpoints are supported. **Default permalinks will not work.**
      + An SSL certificate.

    ## Errors

    asrtasrtarst

    # Authentication

    Requests to most API resources require authentication. Authentication can be preformed by providing API Credentials by using as the username and password via [HTTP Basic Authentication](http://en.wikipedia.org/wiki/Basic_access_authentication) or through request headers.


    Requests to the REST API may only be made over [HTTPS](http://en.wikipedia.org/wiki/HTTP_Secure). Requests made over HTTP will fail.

    ## Basic Authentication

    The preferred authentication method is HTTP Basic Authentication.

    To use HTTP Basic Auth, provide the Consumer Key as the username and the Consumer Secret as the password.

    ```
      curl https://example.tld/wp-json/llms/v1/courses \
        -u ck_d7W85twOWT0poKzDSAQzI7:sk_8bsMmRfjW1HgEFw5ad7BIF
    ```

    ## Header Authentication

    Alternatively, requests may be authenticated by providing the Consumer Key and Consumer secret as the request headers `X-CONSUMER-KEY` and `X-CONSUMER-SECRET`.

    ```
      curl https://example.tld/wp-json/llms/v1/courses \
        -H X-CONSUMER-KEY: ck_d7W85twOWT0poKzDSAQzI7 \
        -H X-CONSUMER-SECRET: sk_8bsMmRfjW1HgEFw5ad7BIF
    ```

  x-logo:
    altText: LifterLMS
    url: "https://gocodebox.github.io/lifterlms-brand/assets/img/png/logo/lifterlms-logo.png"
    href: "https://lifterlms.com/"

servers:
  - url: /wp-json/llms/v1

security:
  - Basic-Authentication: []

tags:

  - name: Access Plans
    description: |
      Access plans allow you to define how LMS content is purchased and accessed by your students.

      The access plans API allows you to create, view, update, and delete courses.

  - name: Courses
    description: |
      The courses API allows you to create, view, update, and delete courses.

  - name: Enrollments
    description: |
      Enrollments are used to track a student's access to content on your website.

      The enrollments API allows you to create, view, update, and delete student enrollments.

  - name: Memberships
    description: |
      The memberships API allows you to create, view, update, and delete memberships.

  - name: Instructors
    description: |
      Instructors are members of your site who have the ability to create and manage LMS content and students. Instructors may be Adminstators, LMS Managers, Instructors, and Instructors Assistants.

      The instructors API allows you to create, view, update, and delete student accounts.

  - name: Sections
    description: |
      The sections API allows you to create, view, update, and delete sections.

      Sections are used within courses to organize content (lessons) into groups.

  - name: Students
    description: |
      Students are members of your site who are (or were) enrolled in your courses and memberships. Students can be any WordPress user account on your site (not exclusively the "student" role).

      The students API allows you to create, view, update, and delete student accounts  as well as view information about the student's LMS content.


x-tagGroups:

  - name: Courses
    tags:
      - Courses
      - Sections
      - Lessons

  - name: Enrollments
    tags:
      - Enrollments

  - name: Memberships
    tags:
      - Memberships

  - name: E-Commerce
    tags:
      - Access Plans

  - name: Users
    tags:
      - Students
      - Instructors
