# https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts
theme:
  logo:
    gutter: 20px
  colors:
    primary:
      main: '#466dd8'
  typography:
    headings:
      fontFamily: 'Montserrat'
      fontWeight: 600
    fontFamily: 'Montserrat'
    fontWeight: 300
    fontSize: 16px
  rightPanel:
    backgroundColor: '#222'
