# https://github.com/Rebilly/ReDoc/blob/master/src/theme.ts
theme:
  logo:
    gutter: 20px 80px 10px 20px
  colors:
    primary:
      main: '#466dd8'
  typography:
    headings:
      fontFamily: 'Montserrat'
      fontWeight: 600
    fontFamily: 'Montserrat'
    fontWeight: 300
    fontSize: 16px
  rightPanel:
    backgroundColor: '#222'

noAutoAuth: true
requiredPropsFirst: true
sortPropsAlphabetically: true

# Use a specific build version
# Currently using rc.22 until https://github.com/Redocly/redoc/issues/1152 is fixed (rc.22 is not the latest release yet).
redocURL: https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.22/bundles/redoc.standalone.js
